language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 10

install:
  - npm

addons:
  sonarcloud:
    organization: "wvandolah" # the key of the org you chose at step #3

script:
  - npm run testCoverage
  - sonar-scanner
