language: node_js

stages:
  - test
  - name: deployDev
    if: branch = dev
git:
  depth: false
  
notifications:
  email: false

node_js:
  - 10


addons:
  sonarcloud:
    organization: "wvandolah" # the key of the org you chose at step #3


testService: &TEST_SERVICE
  install:
    - ls
    - cd backend
    - travis_retry npm install
    - cd -
    - cd tasks
    - travis_retry npm install
    - cd -

  script:
    - cd backend
    - npm run testCoverage
    - cd -
    - cd tasks
    - npm run testCoverage
    - cd -
    - sonar-scanner
  workspaces:
    create:
      name: common
      paths: ./

deployService: &DEPLOY_SERVICE
  install:
    npm install -g serverless
  
  script:
    - cd ${SERVICE_PATH}
    - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
    - travis_retry serverless deploy --stage ${DEPLOY_TO}
    - cd -
  workspaces:
    use: common

jobs:
  include:
    - stage: test
      <<: *TEST_SERVICE
      name: "Test"
    - stage: deploy
      if: branch = dev
      <<: *DEPLOY_SERVICE
      name: "Deploy backend to AWS DEV"
      env: 
        - SERVICE_PATH="backend"
        - DEPLOY_TO="dev"
    - stage: deploy
      if: branch = dev
      <<: *DEPLOY_SERVICE
      name: "Deploy tasks to AWS DEV"
      env: 
        - SERVICE_PATH="tasks"
        - DEPLOY_TO="dev"
    - stage: deploy
      if: branch = master
      <<: *DEPLOY_SERVICE
      name: "Deploy backend to AWS PROD"
      env: 
        - SERVICE_PATH="backend"
        - DEPLOY_TO="prod"
    - stage: deploy
      if: branch = master
      <<: *DEPLOY_SERVICE
      name: "Deploy tasks to AWS PROD"
      env: 
        - SERVICE_PATH="tasks"
        - DEPLOY_TO="prod"
