module.exports = {
  'game-attendants-dev': [
    {
      bulkEmailDestinationStatus: {
        ResponseMetadata: {
          RequestId: 'ca51ba35-5ef5-4783-9940-fd4be33552c4',
        },
        Status: [
          {
            MessageId: '010001739b3314b5-80e8a08e-4ba6-4b42-8e57-a13743ff120e-000000',
            Status: 'Success',
          },
          {
            MessageId: '010001739b3314b5-0c57657c-2b83-42f9-81ea-8ae89f056545-000000',
            Status: 'Success',
          },
        ],
      },
      dateTime: '8/1/2020, 8:30:00 PM',
      gameId: 'gameIdValue',
      opponentName: 'Thunder Cocks',
      players: {
        '-YHC2mghg': {
          email: 'testEmail@test.com',
          firstName: 'Ben',
          id: '-YHC2mghg',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: 'In',
          type: 'full',
        },
        '3wbeJpVR8': {
          email: 'testEmail@test.com',
          firstName: 'Charllie',
          id: '3wbeJpVR8',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: 'Out',
          type: 'sub',
        },
        '58lbS-5MF': {
          email: 'testEmail@test.com',
          firstName: 'Leon',
          id: '58lbS-5MF',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: 'In',
          type: 'full',
        },
        '8Uep1S4Hj': {
          email: 'testEmail@test.com',
          firstName: 'Laz',
          id: '8Uep1S4Hj',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendEmail: true,
          sendText: true,
          smsDelivered: null,
          status: 'In',
          type: 'full',
        },
        bguqMneZ9: {
          email: 'testEmail@test.com',
          firstName: 'John',
          id: 'bguqMneZ9',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: 'In',
          type: 'sub',
        },
        fTKtJMUCy: {
          email: null,
          firstName: 'Brian',
          id: 'fTKtJMUCy',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: 'full',
        },
        JHfzwsoxb: {
          email: 'testEmail@test.com',
          firstName: 'William',
          id: 'JHfzwsoxb',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: 'In',
          type: 'full',
        },
        lkFW9JESh: {
          email: 'testEmail@test.com',
          firstName: 'Jodi',
          id: 'lkFW9JESh',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendEmail: true,
          sendText: true,
          smsDelivered: null,
          status: 'In',
          type: 'full',
        },
        oX2X2eMpU: {
          email: 'testEmail@test.com',
          firstName: 'Robert ',
          id: 'oX2X2eMpU',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: 'full',
        },
        qQiuYVqYt: {
          email: 'testEmail@test.com',
          firstName: 'Jeff',
          id: 'qQiuYVqYt',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: 'In',
          type: 'full',
        },
        'r90-_CJkB': {
          email: null,
          firstName: 'Alex',
          id: 'r90-_CJkB',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: 'In',
          type: 'full',
        },
        S7xGtKMgB: {
          email: 'testEmail@test.com',
          firstName: 'Kevin',
          id: 'S7xGtKMgB',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: 'In',
          type: 'full',
        },
        Um_JNv3so: {
          email: 'testEmail@test.com',
          firstName: 'Ryan',
          id: 'Um_JNv3so',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: 'In',
          type: 'full',
        },
        VyHAjhR5r: {
          email: 'testEmail@test.com',
          firstName: 'Chris',
          id: 'VyHAjhR5r',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: 'In',
          type: 'full',
        },
        'YcwmK13--': {
          email: 'testEmail@test.com',
          firstName: 'Alfonso',
          id: 'YcwmK13--',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: 'full',
        },
        yx7beKq1e: {
          email: 'testEmail@test.com',
          firstName: 'Rodolfo',
          id: 'yx7beKq1e',
          lastName: 'testLastName',
          phoneNumber: '1234567897',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: 'full',
        },
      },
      teamId: 'teamIdValue',
      teamName: 'testTeam',
    },
    {
      dateTime: '8/29/2020, 2:36:31 PM',
      gameId: '7rQx-4ogw',
      opponentName: null,
      players: {
        _6tVhnSou: {
          email: 'william.vandolah@gmail.com',
          firstName: 'William1',
          id: '_6tVhnSou',
          lastName: 'VanDolah',
          phoneNumber: '8178178171',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: null,
        },
        jkJx8zz9K: {
          email: null,
          firstName: 'thevoice',
          id: 'jkJx8zz9K',
          lastName: 'voice',
          phoneNumber: '6822335044‬',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: null,
        },
        'rPOJj33-3': {
          email: 'william.vandolah@gmail.com',
          firstName: 'William4',
          id: 'rPOJj33-3',
          lastName: 'VanDolah',
          phoneNumber: '8178178172',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: null,
        },
        XwwQjOJuE: {
          email: 'william.vandolah@gmail.com',
          firstName: 'William3',
          id: 'XwwQjOJuE',
          lastName: 'VanDolah',
          phoneNumber: '8178178173',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: null,
        },
      },
      teamId: '9hie_SVJi',
      teamName: 'A',
    },
    {
      dateTime: '8/29/2020, 2:36:31 PM',
      gameId: 'gameId',
      opponentName: null,
      players: {
        ZV0xu8M1p: {
          email: 'william.vandolah@gmail.com',
          firstName: 'William1',
          id: 'ZV0xu8M1p',
          lastName: 'VanDolah',
          phoneNumber: '8178178171',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: null,
        },
        jkJx8zz9K: {
          email: null,
          firstName: 'thevoice',
          id: 'jkJx8zz9K',
          lastName: 'voice',
          phoneNumber: '6822335044‬',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: null,
        },
        'rPOJj33-3': {
          email: 'william.vandolah@gmail.com',
          firstName: 'William4',
          id: 'rPOJj33-3',
          lastName: 'VanDolah',
          phoneNumber: '8178178172',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: null,
        },
        XwwQjOJuE: {
          email: 'william.vandolah@gmail.com',
          firstName: 'William3',
          id: 'XwwQjOJuE',
          lastName: 'VanDolah',
          phoneNumber: '8178178173',
          sendText: true,
          smsDelivered: null,
          status: null,
          type: null,
        },
      },
      teamId: 'VyXY1ikPw',
      teamName: 'A',
    },
  ],
  'notification-events-dev': [
    {
      statusType: 0,
      snsMessageId: 'f24cce2f-346d-5ebe-b864-99eb84ef1578',
      retries: 0,
      player: {
        phoneNumber: '8178178171',
        playerId: '_6tVhnSou',
        snsMessageId: 'f24cce2f-346d-5ebe-b864-99eb84ef1578',
      },
      teamInfo: { teamName: 'A', dateTime: '8/29/2020, 2:36:31 PM', gameId: '7rQx-4ogw', teamId: '9hie_SVJi' },
    },
  ],
};
