service: gameattendant

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-domain-manager
  - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    root: wvandolah.com
    api: 
      prod: teamstatus-api.${self:custom.domains.root}
      dev: teamstatus-api-${self:custom.stage}.${self:custom.domains.root}
    ui:
      prod: teamstatus.${self:custom.domains.root}
      dev: teamstatus-${self:custom.stage}.${self:custom.domains.root}
      local: localhost:3000
  customDomain:
    domainName: ${self:custom.domains.api.${self:custom.stage}}
    basePath: ''
    stage: ${self:custom.stage}
    createRoute53Record: true
    certificateName: 'wvandolah.com'
  serverless-offline:
    httpPort: 4000
  tables:
    gameAttendants: "game-attendants-${self:custom.stage}"
    teamPlayers: "team-player-${self:custom.stage}"
  Auth0:
    issuer: https://wvandolah.auth0.com/
    jwksUri: https://wvandolah.auth0.com/.well-known/jwks.json
    audience: gameattendants
  dynamodb:
    stages:
      - ${self:custom.stage}
    start:
      inMemory: true
      migrate: true
      stage: ${opt:stage, 'dev'}
  topic: 
    sendNotificationTopic: "gameattendanttasks-${self:custom.stage}-send-notification-topic"
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    domainName: ${self:custom.domains.ui.${self:custom.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.tables.gameAttendants}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.tables.teamPlayers}"
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: { "Fn::Join" : [":", ["arn:aws:sns:${opt:region, self:provider.region}", { "Ref" : "AWS::AccountId" }, "${self:custom.topic.sendNotificationTopic}" ] ]  }
    - Effect: Allow
      Action:
        - SES:SendBulkTemplatedEmail
      Resource: "*"


functions:
  authFn:
    handler: src/service/authFn.authFn
    environment:
      jwksUri: ${self:custom.Auth0.jwksUri}
      audience: ${self:custom.Auth0.audience}
      issuer: ${self:custom.Auth0.issuer}
  sendStatusRequest:
    handler: src/controller/sendStatus.sendStatusRequest
    environment:
      tableGameAttendants: ${self:custom.tables.gameAttendants}
      sendNotificationTopicArn: { "Fn::Join" : [":", ["arn:aws:sns:${opt:region, self:provider.region}", { "Ref" : "AWS::AccountId" }, "${self:custom.topic.sendNotificationTopic}" ] ]  }
    events:
      - http:
          path: status
          method: post
          cors: true
          authorizer: authFn
  resendStatusRequest:
    handler: src/controller/sendStatus.resendStatusRequest
    environment:
      tableGameAttendants: ${self:custom.tables.gameAttendants}
      sendNotificationTopicArn: { "Fn::Join" : [":", ["arn:aws:sns:${opt:region, self:provider.region}", { "Ref" : "AWS::AccountId" }, "${self:custom.topic.sendNotificationTopic}" ] ]  }
    events:
      - http:
          path: resend
          method: post
          cors: true
          authorizer: authFn
  searchStatusRequest:
    handler: src/controller/status.searchStatuses
    environment:
      tableGameAttendants: ${self:custom.tables.gameAttendants}
    events:
      - http:
          path: status
          method: get
          cors: true
          authorizer: authFn
  deleteStatusRequest:
    handler: src/controller/status.deleteStatus
    environment:
      tableGameAttendants: ${self:custom.tables.gameAttendants}
      sendNotificationTopicArn: { "Fn::Join" : [":", ["arn:aws:sns:${opt:region, self:provider.region}", { "Ref" : "AWS::AccountId" }, "${self:custom.topic.sendNotificationTopic}" ] ]  }
    events:
      - http:
          path: status
          method: delete
          cors: true
          authorizer: authFn
  updatePlayerStatusRequest:
    handler: src/controller/status.updatePlayerStatus
    environment:
      tableGameAttendants: ${self:custom.tables.gameAttendants}
    events:
      - http:
          path: playerStatus
          method: put
          cors: true
  searchPlayerStatusRequest:
    handler: src/controller/status.searchStatus
    environment:
      tableGameAttendants: ${self:custom.tables.gameAttendants}
    events:
      - http:
          path: playerStatus
          method: get
          cors: true
  createTeamPlayerRequest:
    handler: src/controller/teamPlayers.create
    environment:
      tableTeamPlayers: ${self:custom.tables.teamPlayers}
    events:
      - http:
          path: teamPlayers
          method: post
          cors: true
          authorizer: authFn
  searchTeamPlayerRequest:
    handler: src/controller/teamPlayers.search
    environment:
      tableTeamPlayers: ${self:custom.tables.teamPlayers}
    events:
      - http:
          path: teamPlayers
          method: get
          cors: true
          authorizer: authFn
  deleteTeamPlayerRequest:
    handler: src/controller/teamPlayers.deleteTeamPlayer
    environment:
      tableTeamPlayers: ${self:custom.tables.teamPlayers}
    events:
      - http:
          path: teamPlayers
          method: delete
          cors: true
          authorizer: authFn
resources:
  Resources:
    gameAttendants:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tables.gameAttendants}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: S
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
          - AttributeName: gameId
            KeyType: RANGE
    teamPlayers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tables.teamPlayers}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: teamId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: teamId
            KeyType: RANGE
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
